name: build-bluez

on:
  - push

jobs:
  build_docker:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}.${{ matrix.platform }}
      cancel-in-progress: false
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        version:
          - "5.55"
          - "5.56"
          - "5.57"
          - "5.58"
          - "5.59"
          - "5.60"
          - "5.61"
          - "5.62"
          - "5.63"
          - "5.64"
          - "5.65"
          - "5.66"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          ./scripts/cp-build.sh ${{ matrix.platform }} ${{ matrix.version }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bluez
          path: dist/*.tar.gz
