name: build-bluez

on:
  - push

jobs:
  build-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64
          # - linux/arm/v7
        version:
          - "5.55"
          # - "5.56"
          # - "5.57"
          # - "5.58"
          # - "5.59"
          # - "5.60"
          # - "5.61"
          # - "5.62"
          # - "5.63"
          # - "5.64"
          # - "5.65"
          - "5.66"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          ./scripts/cp-build.sh ${{ matrix.platform }} ${{ matrix.version }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: build-all
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Uncompress bluez distributions
        run: |
          ls -ltr blez/
          cd blez
          unzip dist.zip
      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: blez/dist/*.tar.gz
